### ISSUE TITLE
Urgent, Prisma playground broken, Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by lastmjs** [prisma/graphql-playground#963] opened 2019-02-11 18:14 UTC
I'm using a Prisma server, and I'm using the playground included in my browser. I'm getting the following error: `Uncaught SyntaxError: Unexpected end of input`

The error is being thrown from the following file:

`http://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js`

All of my GraphQL playgrounds are broken across localhost and a few live Prisma server instances

**Comment by Huvik** [comment] 2019-02-11 18:18
Could you provide more info? Everything works fine in my end.

**Comment by lastmjs** [comment] 2019-02-11 18:24
I'm using Prisma version 1.21.1, I have a Prisma server running on an aws instance. In fact, you can just go here: https://prisma.staging.jillsoffice.com/

Open up the terminal and you can see the issue.

**Comment by Huvik** [comment] 2019-02-11 18:25
For me is working fine, I can't access your endpoint, because it's protected by a secret.

**Comment by lastmjs** [comment] 2019-02-11 18:25
The is no error in your console?

**Comment by lastmjs** [comment] 2019-02-11 18:27
You shouldn't need my secret to see that the error is being thrown. The error is throwing in Chromium and Firefox for me, Chromium 71 and Firefox 64

**Comment by Huvik** [comment] 2019-02-11 18:29
Nothing ![](https://i.imgur.com/HcpYvFf.png)

**Comment by lastmjs** [comment] 2019-02-11 18:33
Are you going directly to `https://prisma.staging.jillsoffice.com` in your browser? I can't even get that screen to load that you have there, I've tried on multiple browsers and another computer

**Comment by lastmjs** [comment] 2019-02-11 18:39
The problem doesn't seem to be with my Prisma server, but with one of the dependencies loading over a cdn. I have changed nothing that should be related with my code, I think the cdn has broken something

**Comment by pantharshit00** [comment] 2019-02-11 18:43
@Huvik I can confirm this.

![image](https://user-images.githubusercontent.com/22195362/52585508-f989c200-2e5a-11e9-9598-25b7f7229a07.png)

I tested clearing cache even different browser but the problem persisted.

**Comment by MartinKolarik** [comment] 2019-02-11 18:47
@pantharshit00 is the error also coming from the http://cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js file? If yes, can you copy/paste its contents here?

**Comment by Huvik** [comment] 2019-02-11 18:47
I tried firefox, safari, brave everything without cache. Maybe something went wrong with CDN.

**Comment by lastmjs** [comment] 2019-02-11 18:50
@MartinKolarik Yes that is where the error is coming from. You want the contents of the file pasted here? You can click the link and see the contents. Or do you want the contents of the error?

**Comment by lastmjs** [comment] 2019-02-11 18:53
I think it is a problem with the cdn, how do we find who can fix that? Also, why is this dependency being loaded over a cdn, and not installed along with all other dependencies with npm?

**Comment by MartinKolarik** [comment] 2019-02-11 18:55
For me and @Huvik the file loads fine, so yes, it would help if you could upload/screenshot the exact response.

>I think it is a problem with the cdn, how do we find who can fix that?

If it's a problem with the CDN, me 😄

**Comment by Huvik** [comment] 2019-02-11 18:59
> I think it is a problem with the cdn, how do we find who can fix that?

You can fix that using cdn option in playground middleware.

>Also, why is this dependency being loaded over a cdn, and not installed along with all other dependencies with npm?

We are using CDN for middlewares, because we want to ship all latest version with playground without updates. You can always specify what version of the playground you want to use. There is a lot of settings you can play with it.

**Comment by pantharshit00** [comment] 2019-02-11 18:59
@lastmjs It loads fine for me now after a hard reload.

**Comment by pantharshit00** [comment] 2019-02-11 19:02
@MartinKolarik The file was giving nothing at first (I am in Asia region btw).

After a couple of hard reload it works fine again

**Comment by Huvik** [comment] 2019-02-11 19:04
I am closing this issue because it's not related to the playground, there is a workaround to use different CDNs or even local package version.

**Closed by Huvik** 2019-02-11 19:04 UTC
Labels: bug/0-needs-info

**Comment by lastmjs** [comment] 2019-02-11 19:06
It's working again for me :)
