### ISSUE TITLE
Schema doesn't refresh without hitting refresh in the browser

### ISSUE THREAD

**Issue by Lumyo** [prisma/graphql-playground#1048] opened 2019-06-25 16:37 UTC
#### This issue pertains to the following package(s):

- [x] GraphQL Playground - Electron App
- [x] GraphQL Playground HTML
- [x] GraphQL Playground
- [ ] GraphQL Playground Express Middleware
- [ ] GraphQL Playground Hapi Middleware
- [ ] GraphQL Playground Koa Middleware
- [ ] GraphQL Playground Lambda Middleware

#### What OS and OS version are you experiencing the issue(s) on?
Windows 10.0.17763 Build 17763

#### What version of graphql-playground(-electron/-middleware) are you experiencing the issue(s) on?
Version 1.7.20

#### What is the expected behavior?
Schema should refresh when I update my code and reboot my server, and the autocomplete should work with new elements added.

#### What is the actual behavior?
Schema doesnt refresh, autocomplete doesnt work for any new element, but the queries on new element of the schema return the data correctly.

**If I use the version 1.7.15 from https://www.graphqlbin.com/v2/6RQ6TM everything works fine**

#### What steps may we take to reproduce the behavior?

Here is my test project :
[graphql-basics.zip](https://github.com/prisma/graphql-playground/files/3326344/graphql-basics.zip)

1] Comment any query or mutation from the resolver and the schema
2] Run the startDev script
3] Open GraphQL playground in the browser
4] Uncomment what you commented at step 1
5] Try to use it in GraphQL playground, the query/mutation works, but autocomplete doesnt, its highlighted red, and the data in the schema tab on the right isnt updated

**Comment by yoshiakis** [comment] 2019-06-25 20:55
Hi @Lumyo, thank you for reporting! It's probably duplicate of #965 so I'm going to close this issue.

**Closed by yoshiakis** 2019-06-25 20:55 UTC
